### ISSUE TITLE
Make item search

### ISSUE THREAD

**Issue by arist0cles** [ChesterCraig/NWEN304-GroupProject-T4#5]

**Comment by arist0cles** [comment]
Basic search is done but it's Case sensitive and only functions on the home page. Will look into  taking it off all the pages except the home page but don't think I'll bother with case sensitivity

**Comment by ChesterCraig** [comment]
I've made item search case insensitive using lower()

**Comment by arist0cles** [comment]
Cheers man. Have updated so you can only search from the homepage
